# Generated by Django 2.2.10 on 2020-04-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ManyToManyField(to='api.Product'),
        ),
    ]
