# Generated by Django 2.2.10 on 2020-04-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200410_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product',
            new_name='products',
        ),
    ]
